spring.application.name=politicas-de-negocio
spring.mongodb.uri=mongodb://leonardoserrate9_db_user:SSq8tf0baVQNXDKA@ac-rjpknn9-shard-00-00.8n1986b.mongodb.net:27017,ac-rjpknn9-shard-00-01.8n1986b.mongodb.net:27017,ac-rjpknn9-shard-00-02.8n1986b.mongodb.net:27017/politicas_negocio_db?tls=true&authSource=admin&replicaSet=atlas-r5g2lc-shard-0&retryWrites=true&w=majority&appName=leosb
spring.mongodb.database=politicas_negocio_db
server.port=8080
app.cors.allowed-origins=http://localhost:*,http://127.0.0.1:*
app.collab.snapshot-interval-ms=5000